# This workflow runs commit to the main branch in the repository.
# 
# This workflow will:
# - Verify the required variables and secrets are set in this GitHub Repository
# - Install node
# - Install the dependencies for the portal
# - Verify Snyk code scans pass (this is required)
# - Publish the built portal into an S3 bucket
#
# This workflow requires the following variables set in this repository's environment:
# ACCOUNT_ID               -> The ACCOUNT ID of the location of the bucket
# S3_BUCKET                -> The S3 bucket to publish the portal to
#
# This workflow requires the following secrets set in this repository's settings:
# SNYK_AUTH                 -> A token to authenticate to Snyk for scans
# 
# The final S3 bucket location will be:
# s3://S3_BUCKET/portals/REPOSITORY_NAME/versions/latest/
name: Momentum Portal Publish (Main Commits)

on:
  push:
    branches:
      - 'main'
    paths:
      - 'portal/**'

env:
  SOURCE_DIRECTORY: portal

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to read repo contents

jobs:
  build-and-publish-portal:
    name: Build and Publish Portal to S3
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Determine the Repository Name of where this Action is running
      # GHA does not conveniently set a context variable with *only* the Repository Name
      - name: Set Repository Name
        id: repo_name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Run Yarn Install
        working-directory: ${{ env.SOURCE_DIRECTORY }}
        run: yarn install

      # Build the portal
      - name: Run Yarn Build
        working-directory: ${{ env.SOURCE_DIRECTORY }}
        run: yarn build

      # Verify Snyk Scans Pass
      - name: Run Snyk
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_AUTH }}
        with:
          args: ${{ vars.SOURCE_DIRECTORY }}/ --severity-threshold=critical

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/momentum-portal-github-oidc
          aws-region: us-east-1

      # Copy our built portal to the S3 bucket
      - name: Deploy to S3
        working-directory: ${{ env.SOURCE_DIRECTORY }}
        run: |
          aws s3 sync \
          ./build \
          s3://${{ env.S3_BUCKET }}/portals/${{ env.REPO_NAME }}/versions/latest/ \
          --cache-control=\"must-revalidate,max-age:0\" --delete