# This workflow runs on manual execution of this workflow via GitHub Actions.
# 
# This workflow will:
# - Verify the required variables and secrets are set in this GitHub Repository
# - Install node
# - Install the dependencies for the portal
# - Publish the built portal into an S3 bucket
#
# This workflow requires the following variables set in this repository's environment:
# ACCOUNT_ID               -> The ACCOUNT ID of the location of the bucket
# S3_BUCKET                -> The S3 bucket to publish the portal to
# 
# The final S3 bucket location will be:
# s3://S3_BUCKET/portals/REPOSITORY_NAME/versions/YYYYMMDD-GITHASH/
name: Momentum Portal Publish (Dispatch)

on:
  workflow_dispatch:

env:
  SOURCE_DIRECTORY: portal

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required to read repo contents

jobs:
  build-and-publish-portal:
    name: Build and Publish Portal to S3
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Determine Version Directory
      - name: Set Portal Version Directory
        id: version
        uses: kineticdata/kinetic-github-actions/dockertag@v1

      # Determine the Repository Name of where this Action is running
      # GHA does not conveniently set a context variable with *only* the Repository Name
      - name: Set Repository Name
        id: repo_name
        run: |
          echo "REPO_NAME=${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}" >> $GITHUB_ENV

      # Verify we were able to parse out the repository name
      - name: Fail if Repository Name Not Set
        if: ${{ !steps.repo_name.outputs.REPO_NAME }}
        uses: actions/github-script@v7
        with:
          script: |
            core.setFailed('The REPO_NAME value was not set in the github actions outputs.')

      # Setup Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install dependencies
      - name: Run Yarn Install
        working-directory: ${{ env.SOURCE_DIRECTORY }}
        run: yarn install

      # Build the portal
      - name: Run Yarn Build
        working-directory: ${{ env.SOURCE_DIRECTORY }}
        run: yarn build


      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.ACCOUNT_ID }}:role/momentum-portal-github-oidc
          aws-region: us-east-1

      # Copy our built portal to the S3 bucket
      - name: Deploy to S3
        working-directory: ${{ env.SOURCE_DIRECTORY }}
        run: |
          aws s3 sync \
          ./build \
          s3://${{ env.S3_BUCKET }}/portals/${{ env.REPO_NAME }}/versions/${{ steps.version.outputs.tag }}/ \
          --cache-control=\"must-revalidate,max-age:0\" --delete